/**
 * Report generation service — produces PDFs from emission + AQI data and
 * writes them under `backend/files/reports/<id>.pdf`. The DB row in `reports`
 * is the source of truth; the file is the artifact.
 */
import fs from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import {
  Prisma,
  ReportFormat,
  ReportType,
  type Report as ReportRow,
} from '@prisma/client';
import { prisma } from '../prisma/client';
import { logger } from '../utils/logger';
import { renderReportPdf, type ReportPdfData } from './pdf/reportPdf';

export const REPORTS_DIR = path.resolve(process.cwd(), 'files', 'reports');
fs.mkdirSync(REPORTS_DIR, { recursive: true });

export interface GenerateOpts {
  type: ReportType;
  periodStart?: Date;
  periodEnd?: Date;
  industryId?: string | null;
  generatedById?: string | null;
}

export async function generateReport(opts: GenerateOpts): Promise<ReportRow> {
  const periodStart = opts.periodStart ?? startOfMonth(new Date());
  const periodEnd = opts.periodEnd ?? new Date();

  // Industry context (if scoped).
  const industry = opts.industryId
    ? await prisma.industry.findUnique({ where: { id: opts.industryId } })
    : null;

  // Get user name for "generated by"
  const generatedBy = opts.generatedById
    ? await getUserName(opts.generatedById)
    : null;

  // Emission logs in window.
  const emissions = await prisma.emissionLog.findMany({
    where: {
      ...(opts.industryId && { industryId: opts.industryId }),
      recordedAt: { gte: periodStart, lte: periodEnd },
    },
    include: { industry: true },
    orderBy: { recordedAt: 'desc' },
    take: 200,
  });

  // Get notices for compliance reports
  const notices = opts.type.includes('COMPLIANCE') ? await getNoticesInPeriod(
    periodStart,
    periodEnd,
    opts.industryId,
  ) : null;

  // AQI data
  const aqi = await safeLatestAqi(periodStart, periodEnd);

  // Calculate totals
  const totals = {
    records: emissions.length,
    co2Kg: sum(emissions.map((e) => num(e.co2Kg))),
    noxKg: sum(emissions.map((e) => num(e.noxKg))),
    soxKg: sum(emissions.map((e) => num(e.soxKg))),
    compliant: emissions.filter((e) => e.overallStatus === 'COMPLIANT').length,
    warning: emissions.filter((e) => e.overallStatus === 'WARNING').length,
    violation: emissions.filter((e) => e.overallStatus === 'VIOLATION').length,
  };

  const id = randomUUID();
  const filename = `${id}.pdf`;
  const filepath = path.join(REPORTS_DIR, filename);
  const storageKey = `reports/${filename}`;
  const title = titleFor(opts.type, periodStart, periodEnd, industry?.name);

  // Prepare PDF data
  const pdfData: ReportPdfData = {
    reportId: id,
    title,
    typeLabel: humanType(opts.type),
    periodStart,
    periodEnd,
    generatedAt: new Date(),
    generatedBy,
    scopeLabel: industry ? `${industry.name} (${industry.sector})` : 'All industries',
    totals,
    rows: emissions.slice(0, 30).map((e) => ({
      recordedAt: e.recordedAt,
      industry: e.industry?.name ?? 'Unknown',
      co2Kg: num(e.co2Kg),
      noxKg: num(e.noxKg),
      soxKg: num(e.soxKg),
      status: e.overallStatus,
    })),
    rowsOmitted: Math.max(0, emissions.length - 30),
    aqi: aqi.map((a) => ({
      city: a.city,
      values: {
        pm25: a.values.pm25 ? { value: a.values.pm25.value, unit: a.values.pm25.unit } : undefined,
        pm10: a.values.pm10 ? { value: a.values.pm10.value, unit: a.values.pm10.unit } : undefined,
        no2: a.values.no2 ? { value: a.values.no2.value, unit: a.values.no2.unit } : undefined,
        so2: a.values.so2 ? { value: a.values.so2.value, unit: a.values.so2.unit } : undefined,
        co: a.values.co ? { value: a.values.co.value, unit: a.values.co.unit } : undefined,
      },
    })),
    notices,
  };

  const pageCount = await renderReportPdf(pdfData, filepath);

  const stats = fs.statSync(filepath);
  const report = await prisma.report.create({
    data: {
      type: opts.type,
      format: ReportFormat.PDF,
      title,
      periodStart,
      periodEnd,
      storageKey,
      sizeBytes: stats.size,
      pageCount,
      generatedById: opts.generatedById ?? null,
      industryId: opts.industryId ?? null,
    },
  });

  logger.info(
    { reportId: report.id, sizeBytes: stats.size, pages: pageCount },
    'PDF report generated',
  );
  return report;
}

// -----------------------------------------------------------------------------
// Helper functions
// -----------------------------------------------------------------------------

function num(d: Prisma.Decimal | number | null | undefined): number {
  if (d === null || d === undefined) return 0;
  if (typeof d === 'number') return d;
  return Number(d.toString());
}

function sum(xs: number[]): number {
  return xs.reduce((a, b) => a + b, 0);
}

function startOfMonth(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth(), 1);
}

function humanType(t: ReportType): string {
  switch (t) {
    case 'EMISSIONS_MONTHLY':
      return 'Monthly Emissions';
    case 'EMISSIONS_QUARTERLY':
      return 'Quarterly Emissions';
    case 'COMPLIANCE_QUARTERLY':
      return 'Quarterly Compliance';
    case 'ANNUAL_REPORT':
      return 'Annual Report';
    case 'FACILITY_AUDIT':
      return 'Facility Audit';
    case 'AI_INSIGHTS':
      return 'AI Insights';
    default:
      return 'Custom';
  }
}

function titleFor(
  t: ReportType,
  start: Date,
  end: Date,
  industryName?: string | null,
): string {
  const monthYear = `${monthName(start)} ${start.getFullYear()}`;
  const base = (() => {
    switch (t) {
      case 'EMISSIONS_MONTHLY':
        return `Monthly Emissions — ${monthYear}`;
      case 'EMISSIONS_QUARTERLY':
        return `Quarterly Emissions — ${monthYear}`;
      case 'COMPLIANCE_QUARTERLY':
        return `Quarterly Compliance — ${monthYear}`;
      case 'ANNUAL_REPORT':
        return `Annual Report — ${start.getFullYear()}`;
      case 'FACILITY_AUDIT':
        return `Facility Audit — ${monthYear}`;
      case 'AI_INSIGHTS':
        return `AI Insights — ${monthYear}`;
      default:
        return `Report — ${monthYear}`;
    }
  })();
  return industryName ? `${base}  ·  ${industryName}` : base;
}

function monthName(d: Date): string {
  return [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ][d.getMonth()]!;
}

async function getUserName(userId: string): Promise<string | null> {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { fullName: true },
  });
  return user?.fullName || null;
}

async function getNoticesInPeriod(
  start: Date,
  end: Date,
  industryId?: string | null,
): Promise<ReportPdfData['notices']> {
  const where: any = {
    issuedAt: { gte: start, lte: end },
  };
  if (industryId) where.industryId = industryId;

  const notices = await prisma.notice.findMany({
    where,
    include: { industry: { select: { name: true } } },
    orderBy: { issuedAt: 'desc' },
    take: 50,
  });

  return notices.map((n) => ({
    noticeNumber: n.noticeNumber,
    industry: n.industry?.name ?? 'Unknown',
    severity: n.severity,
    status: n.status,
    issuedAt: n.issuedAt,
  }));
}

// -----------------------------------------------------------------------------
// Cross-PR compatibility: AQI fetch is a no-op if the model doesn't exist yet.
// -----------------------------------------------------------------------------

async function safeLatestAqi(
  start: Date,
  end: Date,
): Promise<Array<{
  city: string;
  values: Record<string, { value: number; unit: string }>;
}>> {
  const p = prisma as unknown as Record<string, { findMany?: Function }>;
  if (!p.airQualityReading || typeof p.airQualityReading.findMany !== 'function') {
    return [];
  }
  try {
    const rows = (await p.airQualityReading.findMany({
      where: { recordedAt: { gte: start, lte: end } },
      orderBy: { recordedAt: 'desc' },
      take: 500,
    })) as Array<{
      city: string;
      parameter: string;
      value: number;
      unit: string;
      recordedAt: Date;
    }>;

    // Group by city and parameter
    const cityMap = new Map<string, Record<string, { value: number; unit: string }>>();

    for (const r of rows) {
      let entry = cityMap.get(r.city);
      if (!entry) {
        entry = {};
        cityMap.set(r.city, entry);
      }
      if (!entry[r.parameter]) {
        entry[r.parameter] = { value: r.value, unit: r.unit };
      }
    }

    return Array.from(cityMap.entries()).map(([city, values]) => ({
      city,
      values,
    }));
  } catch (err) {
    logger.warn({ err }, 'AQI fetch for report failed (non-fatal)');
    return [];
  }
}