/**
 * Pure renderer for emission / compliance reports. No Prisma, no env — takes
 * plain data and writes a PDF, so it can be unit-tested in isolation.
 */
import {
  C, MARGIN, brandBar, contentWidth, createDoc, dashedRule, drawTable, fmtDate,
  fmtDateTime, fmtNum, kpiGrid, kv, pdfSafe, renderToFile, sectionTitle, type Doc,
} from './pdfKit';

export interface ReportPdfData {
  reportId: string;
  title: string;
  typeLabel: string;
  periodStart: Date;
  periodEnd: Date;
  generatedAt: Date;
  generatedBy: string | null;
  scopeLabel: string;
  totals: {
    records: number;
    co2Kg: number;
    noxKg: number;
    soxKg: number;
    compliant: number;
    warning: number;
    violation: number;
  };
  rows: Array<{
    recordedAt: Date;
    industry: string;
    co2Kg: number;
    noxKg: number;
    soxKg: number;
    status: string;
  }>;
  rowsOmitted: number;
  aqi: Array<{ city: string; values: Record<string, { value: number; unit: string }> }>;
  notices: Array<{
    noticeNumber: string;
    industry: string;
    severity: string;
    status: string;
    issuedAt: Date | null;
  }> | null; // null = section not applicable for this report type
}

export function renderReportPdf(data: ReportPdfData, filepath: string): Promise<number> {
  const doc = createDoc(data.title, 'Emission compliance report');
  const footer = `CLIMACORE  |  ${data.typeLabel}  |  Report ${data.reportId.slice(0, 8)}  |  Auto-generated`;
  return renderToFile(doc, filepath, footer, (d) => {
    header(d, data);
    summary(d, data);
    emissionsTable(d, data);
    if (data.notices) noticesTable(d, data.notices);
    aqiTable(d, data);
  });
}

function header(doc: Doc, data: ReportPdfData): void {
  brandBar(doc);
  doc.x = MARGIN.left;
  doc.y = MARGIN.top - 10;
  doc.font('Helvetica-Bold').fontSize(22).fillColor(C.ink).text('CLIMACORE');
  doc.font('Helvetica').fontSize(8).fillColor(C.muted).text('AI-POWERED EMISSION INTELLIGENCE');
  dashedRule(doc, doc.y + 6, 1.2);
  doc.y += 14;

  doc.x = MARGIN.left;
  doc.font('Helvetica-Bold').fontSize(16).fillColor(C.ink).text(pdfSafe(data.title), {
    width: contentWidth(doc),
  });
  doc.moveDown(0.3);
  kv(doc, 'Period', `${fmtDate(data.periodStart)}  to  ${fmtDate(data.periodEnd)}`);
  kv(doc, 'Generated', fmtDateTime(data.generatedAt));
  if (data.generatedBy) kv(doc, 'Generated by', data.generatedBy);
  kv(doc, 'Report type', data.typeLabel);
  kv(doc, 'Scope', data.scopeLabel);
  doc.moveDown(0.8);
}

function summary(doc: Doc, data: ReportPdfData): void {
  sectionTitle(doc, 'SUMMARY');
  const t = data.totals;
  kpiGrid(doc, [
    { label: 'Emission records', value: String(t.records) },
    { label: 'Total CO2', value: `${fmtNum(t.co2Kg)} kg` },
    { label: 'Total NOx', value: `${fmtNum(t.noxKg)} kg` },
    { label: 'Total SOx', value: `${fmtNum(t.soxKg)} kg` },
    { label: 'Compliant', value: String(t.compliant), color: C.green },
    { label: 'Warning', value: String(t.warning), color: C.amber },
    { label: 'Violation', value: String(t.violation), color: C.red },
    { label: 'AQI cities', value: String(data.aqi.length) },
  ]);
  doc.moveDown(0.6);
}

function emissionsTable(doc: Doc, data: ReportPdfData): void {
  sectionTitle(doc, 'EMISSION RECORDS');
  if (data.rows.length === 0) {
    doc.x = MARGIN.left;
    doc.font('Helvetica-Oblique').fontSize(10).fillColor(C.muted).text(
      'No emission records were submitted in this period.',
      { align: 'center', width: contentWidth(doc) },
    );
    doc.moveDown(0.8);
    return;
  }
  drawTable(
    doc,
    [
      { header: 'Recorded', width: 90 },
      { header: 'Industry', width: 140 },
      { header: 'CO2 (kg)', width: 70, align: 'right' },
      { header: 'NOx (kg)', width: 65, align: 'right' },
      { header: 'SOx (kg)', width: 65, align: 'right' },
      { header: 'Status', width: 65 },
    ],
    data.rows.map((r) => [
      fmtDate(r.recordedAt), r.industry, fmtNum(r.co2Kg), fmtNum(r.noxKg),
      fmtNum(r.soxKg), r.status,
    ]),
  );
  if (data.rowsOmitted > 0) {
    doc.moveDown(0.3);
    doc.font('Helvetica-Oblique').fontSize(8).fillColor(C.muted)
      .text(`... and ${data.rowsOmitted} more records not shown (totals above include all).`);
  }
  doc.moveDown(0.8);
}

function noticesTable(doc: Doc, notices: NonNullable<ReportPdfData['notices']>): void {
  sectionTitle(doc, 'COMPLIANCE NOTICES ISSUED IN PERIOD');
  if (notices.length === 0) {
    doc.x = MARGIN.left;
    doc.font('Helvetica-Oblique').fontSize(10).fillColor(C.muted)
      .text('No compliance notices were issued in this period.', {
        align: 'center', width: contentWidth(doc),
      });
    doc.moveDown(0.8);
    return;
  }
  drawTable(
    doc,
    [
      { header: 'Notice No.', width: 110 },
      { header: 'Industry', width: 170 },
      { header: 'Severity', width: 70 },
      { header: 'Status', width: 80 },
      { header: 'Issued', width: 65 },
    ],
    notices.map((n) => [
      n.noticeNumber, n.industry, n.severity, n.status,
      n.issuedAt ? fmtDate(n.issuedAt) : '-',
    ]),
  );
  doc.moveDown(0.8);
}

function aqiTable(doc: Doc, data: ReportPdfData): void {
  if (data.aqi.length === 0) return;
  sectionTitle(doc, 'AMBIENT AIR QUALITY (LATEST PER CITY IN PERIOD)');
  const cell = (v?: { value: number; unit: string }) =>
    v ? `${fmtNum(v.value)} ${v.unit}` : '-';
  drawTable(
    doc,
    [
      { header: 'City', width: 120 },
      { header: 'PM2.5', width: 75 },
      { header: 'PM10', width: 75 },
      { header: 'NO2', width: 75 },
      { header: 'SO2', width: 75 },
      { header: 'CO', width: 75 },
    ],
    data.aqi.slice(0, 20).map((a) => [
      a.city, cell(a.values.pm25), cell(a.values.pm10), cell(a.values.no2),
      cell(a.values.so2), cell(a.values.co),
    ]),
  );
}